# Generated by Django 4.0.6 on 2022-07-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sibal',
            fields=[
                ('id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sibal',
                'managed': False,
            },
        ),
    ]
