# Generated by Django 4.0.6 on 2022-07-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_num', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_num', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('member_pwd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('golf_career', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sibal',
        ),
        migrations.CreateModel(
            name='SwingResult',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend_app.member')),
                ('swing_date', models.DateTimeField()),
                ('address_result', models.IntegerField(blank=True, null=True)),
                ('top_result', models.IntegerField(blank=True, null=True)),
                ('finish_result', models.IntegerField(blank=True, null=True)),
                ('address_img', models.CharField(blank=True, max_length=200, null=True)),
                ('top_img', models.CharField(blank=True, max_length=200, null=True)),
                ('finish_img', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'swing_result',
                'managed': False,
            },
        ),
    ]
